### ISSUE TITLE
Open lidar-based DSM and DTM dataset for ~72% of UK

### ISSUE THREAD

**Issue by robhawkes** [valhalla/skadi#30]
_I'm currently using Valhalla as a fallback for working out the ground height below buildings in [Polygon City](https://github.com/polygon-city/polygon-city-app) (another Mapzen project) and having more accurate height data in urban environments would be very, very useful for us (as it would with my own project, [ViziCities](https://github.com/vizicities/vizicities/tree/0.2.0)) – SRTM just doesn't cut it for the accuracy we need, both horizontally and vertically._

_Let me know if this isn't helpful here – I saw that you wanted suggestions for open elevation datasets to use and assumed this was the best place. I have plenty more to suggest if it's helpful._

---

The Environment Agency in the UK [recently released the first tranche of their LIDAR elevation data for around 72% of the UK](https://environmentagency.blog.gov.uk/2015/09/18/laser-surveys-light-up-open-data/) – including DSM and DTM ASCII files at horizontal resolutions of 25cm, 50cm, 1m, and 2m. This data has been released under an [Open Government License](http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/), which is compatible with the [CC-BY 4.0 license](https://creativecommons.org/licenses/by/4.0/).

There's a _lot_ of data and currently the only way to download it is manually through a portal. The data is also more verbose than it needs to be due to unnecessary decimal accuracy and the EA are looking to reduce this overhead (and the file-size) in the near future.

There are 2 potential approaches to automate the download of the data:

- The download links are easy to automate (based on the Ordnance Survey National Grid) and so it would be possible to batch them all up and slowly work through them
- I have contacts at the Environment Agency who may be able to help get access a bulk download or some other bulk export

**Comment by kevinkreiser** [comment]
@robhawkes yes as many suggestions as you can muster would be great. we don't currently have a schedule for adding new datasets, but once we have a decent list going we can start to do that. as you point out, with each new data set we'll have to jump through the hoops to get it into the proper format but that's part of the fun ;)

one question i have for you though. what kind of horizontal resolution are you looking for? Currently we are doing 1 arc second a la srtm (lower res datasets are upscaled). in terms of disk space, much higher than that becomes prohibitive (when you are dealing with the whole world). we could start to do variable resolution tiles internally but the complications that brings (and possibly decrease in performance) is probably not worth it. so if we integrate this, would you be expecting 25cm resolution or could you make due with something more like 10 meters?

**Comment by nvkelso** [comment]
Migrated to: https://github.com/mapzen/joerd/issues/25.
