### ISSUE TITLE
Available data sets for U.S. states of various resolutions

### ISSUE THREAD

**Issue by glw** [valhalla/skadi#31]
A list was put together on Wikipedia here:
https://en.wikipedia.org/wiki/National_Lidar_Dataset_%28United_States%29

If you do, do an update can you start with Illinois? :)
https://clearinghouse.isgs.illinois.edu/data/elevation/illinois-height-modernization-ilhmp-lidar-data

Thanks!

**Comment by kevinkreiser** [comment]
Nice, thanks for this! We'll definitely let everyone know which datasets and when we plan to make another cut of the elevation data tiles.

**Comment by glw** [comment]
Excellent. Thanks! Keep up the great work.

**Comment by nvkelso** [comment]
Migrated to: https://github.com/mapzen/joerd/issues/26.
