### ISSUE TITLE
Additional data sources

### ISSUE THREAD

**Issue by chrislukic** [valhalla/skadi#63]
I'm currently using the MapZen elevation API to correct the GPS elevations of running routes.  Unfortunately the data can be far off reality in many cities. For example in the attached file I'm getting slopes of > 20% at points along a flat route along the Hudson near Jersey City.

Are there any plans to add additional data sources such as NED to improve the quality of these results?

**Comment by kevinkreiser** [comment]
NED has been added to the elevation tiles and released here: https://aws.amazon.com/blogs/publicsector/announcing-terrain-tiles-on-aws-a-qa-with-mapzen/

We are tracking the issues of making use of these new better data sources here issue over here: https://github.com/valhalla/skadi/issues/47

Essentially all we need to do is pull down this data to the service but we just havent carved out the time  yet.
